In [40]:
import pandas as pd
import numpy as np
import tensorflow as tf
import keras


In [45]:
data = {
    "height": [150,155,175,162,180,152,166,174,182,195],
    "weight":[40,45,55,60,78,54,66,63,88,96],
    "gender" : [0,0,1,0,1,1,1,0,1,1]
        }
df = pd.DataFrame(data)
df

height  weight  gender
0     150      40       0
1     155      45       0
2     175      55       1
3     162      60       0
4     180      78       1
5     152      54       1
6     166      66       1
7     174      63       0
8     182      88       1
9     195      96       1

In [46]:
df_label = df.pop("gender")
df_label

0    0
1    0
2    1
3    0
4    1
5    1
6    1
7    0
8    1
9    1
Name: gender, dtype: int64

In [47]:
df

height  weight
0     150      40
1     155      45
2     175      55
3     162      60
4     180      78
5     152      54
6     166      66
7     174      63
8     182      88
9     195      96

In [56]:
data = {
    "height": [150,155,175,162,180,152,166,174,182,195,40,45,55,60,78,54,66,63,88,96],
    # "weight":[],
    # "gender" : [0,0,1,0,1,1,1,0,1,1]
        }
dff = pd.DataFrame(data)
dff.describe()

height
count   20.000000
mean   116.800000
std     55.993045
min     40.000000
25%     62.250000
50%    123.000000
75%    168.000000
max    195.000000

In [48]:
df.describe().transpose()

count   mean        std    min     25%    50%     75%    max
height   10.0  169.1  14.647336  150.0  156.75  170.0  178.75  195.0
weight   10.0   64.5  18.050854   40.0   54.25   61.5   75.00   96.0

In [49]:
train_mean = df.mean()
train_std = df.std()

train_df = (df - train_mean) / train_std
# val_df = (val_df - train_mean) / train_std
# test_df = (test_df - train_mean) / train_std
train_df

height    weight
0 -1.303991 -1.357276
1 -0.962632 -1.080281
2  0.402804 -0.526291
3 -0.484730 -0.249296
4  0.744163  0.747887
5 -1.167448 -0.581690
6 -0.211643  0.083099
7  0.334532 -0.083099
8  0.880706  1.301877
9  1.768240  1.745070

In [50]:
import numpy as np
import keras
# from tensorflow import keras
data = df.to_numpy()  # Convert DataFrame to NumPy array

layer = keras.layers.Normalization(axis=None)
layer.adapt(data)
n_df = layer(data)
n_df

<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
array([[ 0.6083341 , -1.4072309 ],
       [ 0.6999507 , -1.3156143 ],
       [ 1.0664171 , -1.1323811 ],
       [ 0.82821393, -1.0407646 ],
       [ 1.1580336 , -0.71094483],
       [ 0.6449807 , -1.1507044 ],
       [ 0.9015072 , -0.93082464],
       [ 1.0480938 , -0.9857946 ],
       [ 1.1946803 , -0.52771163],
       [ 1.4328834 , -0.38112506]], dtype=float32)>

In [52]:
layer.mean.numpy()

array([[116.8]], dtype=float32)

In [59]:
layer.variables

[<tf.Variable 'mean:0' shape=() dtype=float32, numpy=116.8>,
 <tf.Variable 'variance:0' shape=() dtype=float32, numpy=2978.46>,
 <tf.Variable 'count:0' shape=() dtype=int64, numpy=20>]

In [37]:
# Retrieve the mean and variance from the layer
mean = layer.mean.numpy()
variance = layer.variance.numpy()
std_dev = np.sqrt(variance)

# Function to revert normalization
def revert_normalization(normalized_data, mean, std_dev):
    return normalized_data * std_dev + mean

# Revert the normalization
original_data = revert_normalization(n_df, mean, std_dev)

print(original_data)

tf.Tensor(
[[12.       40.      ]
 [15.       45.      ]
 [45.       55.      ]
 [34.       60.      ]
 [21.       78.      ]
 [42.       54.      ]
 [36.       66.      ]
 [14.000002 35.      ]
 [22.       88.      ]
 [25.       96.      ]], shape=(10, 2), dtype=float32)


In [ ]:
classifier = keras.models