In [9]:
import tensorflow as tf
import keras
from keras import layers
import pandas as pd
import numpy as np
print(f'TensorFlow version: {tf.__version__}')

TensorFlow version: 2.11.0


In [10]:
df= pd.read_parquet(r"D:\RND\Machine_Learning\Datasets/clean_dataset_ml_50_id.parquet")
df['creation_time'] = pd.to_datetime(df['creation_time'])
df.set_index(['creation_time'],drop= True, inplace= True)
df.sort_index(inplace=True)
df.reset_index(drop=True,inplace=True)
df

temperature_2m  relative_humidity_2m  apparent_temperature  \
0                 12.1                    95                  10.8   
1                  7.4                    97                   5.2   
2                 10.5                    79                   7.0   
3                  7.6                    95                   4.9   
4                  7.7                    95                   5.1   
...                ...                   ...                   ...   
225618            17.0                    37                  13.3   
225619            17.0                    37                  13.4   
225620            18.7                    39                  14.6   
225621            17.1                    33                  12.4   
225622            18.1                    38                  14.7   

        wind_speed_10m  wind_speed_100m  consumed_unit   lag1   lag2  lag3  \
0                 11.4             21.6            0.0   0.00   0.00  0.00   
1                 10.0             19.6            0.0   0.00   0.00  0.00   
2                 18.5             32.1            2.0   0.00   0.00  0.00   
3                 13.3             25.2            0.0   0.00   0.00  0.00   
4                 12.1             23.7            0.0   0.00   0.00  0.00   
...                ...              ...            ...    ...    ...   ...   
225618            13.5             25.2            0.3   0.29   0.31  2.90   
225619            12.7             24.8           13.6  13.85  13.69  2.40   
225620            19.1             34.9            0.1   0.00   0.10  0.00   
225621            18.6             31.4            0.0   0.20   0.10  0.10   
225622            12.6             25.1            0.0   0.00   0.00  5.97   

        lag4   lag5  day  hour  month  dayofweek  dayofyear  label_sensor_id  
0       0.00  0.000    1     0      1          0          1                0  
1       0.00  0.000    1     0      1          0          1               15  
2       0.00  0.000    1     0      1          0          1               12  
3       0.00  0.000    1     0      1          0          1               45  
4       0.00  0.000    1     0      1          0          1               11  
...      ...    ...  ...   ...    ...        ...        ...              ...  
225618  2.70  0.045   25    23      2          6         56               30  
225619  2.74  7.600   25    23      2          6         56               29  
225620  0.10  0.000   25    23      2          6         56               27  
225621  0.30  0.400   25    23      2          6         56               23  
225622  0.00  0.000   25    23      2          6         56               50  

[225623 rows x 17 columns]

In [11]:
df_features = df.copy()
df_labels = df_features.pop('consumed_unit')

In [12]:
df_features

temperature_2m  relative_humidity_2m  apparent_temperature  \
0                 12.1                    95                  10.8   
1                  7.4                    97                   5.2   
2                 10.5                    79                   7.0   
3                  7.6                    95                   4.9   
4                  7.7                    95                   5.1   
...                ...                   ...                   ...   
225618            17.0                    37                  13.3   
225619            17.0                    37                  13.4   
225620            18.7                    39                  14.6   
225621            17.1                    33                  12.4   
225622            18.1                    38                  14.7   

        wind_speed_10m  wind_speed_100m   lag1   lag2  lag3  lag4   lag5  day  \
0                 11.4             21.6   0.00   0.00  0.00  0.00  0.000    1   
1                 10.0             19.6   0.00   0.00  0.00  0.00  0.000    1   
2                 18.5             32.1   0.00   0.00  0.00  0.00  0.000    1   
3                 13.3             25.2   0.00   0.00  0.00  0.00  0.000    1   
4                 12.1             23.7   0.00   0.00  0.00  0.00  0.000    1   
...                ...              ...    ...    ...   ...   ...    ...  ...   
225618            13.5             25.2   0.29   0.31  2.90  2.70  0.045   25   
225619            12.7             24.8  13.85  13.69  2.40  2.74  7.600   25   
225620            19.1             34.9   0.00   0.10  0.00  0.10  0.000   25   
225621            18.6             31.4   0.20   0.10  0.10  0.30  0.400   25   
225622            12.6             25.1   0.00   0.00  5.97  0.00  0.000   25   

        hour  month  dayofweek  dayofyear  label_sensor_id  
0          0      1          0          1                0  
1          0      1          0          1               15  
2          0      1          0          1               12  
3          0      1          0          1               45  
4          0      1          0          1               11  
...      ...    ...        ...        ...              ...  
225618    23      2          6         56               30  
225619    23      2          6         56               29  
225620    23      2          6         56               27  
225621    23      2          6         56               23  
225622    23      2          6         56               50  

[225623 rows x 16 columns]

In [13]:
tf.keras.layers.Normalization(
    axis=-1, mean=None, variance=None, invert=False,
)
layer = keras.layers.Normalization(axis=None)
layer.adapt(df_features)
df_n = layer(df_features)
df_n

<tf.Tensor: shape=(225623, 16), dtype=float32, numpy=
array([[-0.03432363,  5.249547  , -0.11718289, ..., -0.805552  ,
        -0.74181414, -0.805552  ],
       [-0.3338917 ,  5.3770227 , -0.47411504, ..., -0.805552  ,
        -0.74181414,  0.15051621],
       [-0.13630426,  4.2297406 , -0.35938686, ..., -0.805552  ,
        -0.74181414, -0.04069744],
       ...,
       [ 0.38634643,  1.6802255 ,  0.12502107, ..., -0.42312473,
         2.7637694 ,  0.9153708 ],
       [ 0.28436577,  1.2977982 , -0.01520231, ..., -0.42312473,
         2.7637694 ,  0.6604193 ],
       [ 0.34810367,  1.6164876 ,  0.13139483, ..., -0.42312473,
         2.7637694 ,  2.3813422 ]], dtype=float32)>

In [14]:
class CustomModel(keras.Model):
    def train_step(self, data):
        # Unpack the data. Its structure depends on your model and
        # on what you pass to `fit()`.
        x, y = data

        with tf.GradientTape() as tape:
            y_pred = self(x, training=True)  # Forward pass
            # Compute the loss value
            # (the loss function is configured in `compile()`)
            loss = self.compute_loss(y=y, y_pred=y_pred)

        # Compute gradients
        trainable_vars = self.trainable_variables
        gradients = tape.gradient(loss, trainable_vars)
        # Update weights
        self.optimizer.apply_gradients(zip(gradients, trainable_vars))
        # Update metrics (includes the metric that tracks the loss)
        for metric in self.metrics:
            if metric.name == "loss":
                metric.update_state(loss)
            else:
                metric.update_state(y, y_pred)
        # Return a dict mapping metric names to current value
        return {m.name: m.result() for m in self.metrics}

In [17]:
import numpy as np

# Construct and compile an instance of CustomModel
inputs = keras.Input(shape=(16,))
outputs = keras.layers.Dense(1)(inputs)
model = CustomModel(inputs, outputs)
model.compile(optimizer="adam", loss="mse", metrics=["mae"])



In [18]:
# Just use `fit` as usual
model.fit(df_features, df_labels, epochs=3)

Epoch 1/3
7051/7051 [==============================] - 7s 868us/step - loss: 6.1412
Epoch 2/3
7051/7051 [==============================] - 6s 816us/step - loss: 2.7054
Epoch 3/3
7051/7051 [==============================] - 6s 813us/step - loss: 2.6967


In [3]:
column_indices = {name: i for i, name in enumerate(df.columns)}

n = len(df)
train_df = df[0:int(n*0.8)]
# val_df = df[int(n*0.7):int(n*0.9)]
test_df = df[int(n*0.8):]
print("train_df:",len(train_df),"test_df:",len(test_df))
num_features = df.shape[1]
train_features = train_df.copy()
test_features = test_df.copy()

train_labels = train_features.pop('consumed_unit')
test_labels = test_features.pop('consumed_unit')


train_df: 180498 test_df: 45125


## When to use a Sequential model
A Sequential model is appropriate for a plain stack of layers where each layer has exactly one input tensor and one output tensor.

In [31]:
from tensorflow.keras import layers, models, optimizers, losses
# Redefine the model with correct number of output neurons
model = keras.Sequential(
    [
    layers.Dense(64, activation='relu', input_shape=(16,)),  # First hidden layer with 64 units
    layers.Dense(32, activation='relu'),                     # Second hidden layer with 32 units
    layers.Dense(1) 
    ]
)

# Compile the model
model.compile(optimizer=optimizers.Adam(learning_rate=0.001),
              loss=losses.MeanSquaredError(),  # Regression loss
              metrics=['mae'])  # Mean Absolute Error as a metric

history = model.fit(
    train_features,        # Features for training
    train_labels,          # Labels for training
    validation_data=(test_features, test_labels),  # Validation data
    epochs=50,             # Number of epochs
    batch_size=32          # Batch size
)

Epoch 1/50
5641/5641 [==============================] - 7s 1ms/step - loss: 3.8542 - mae: 0.8641 - val_loss: 2.6589 - val_mae: 0.7506
Epoch 2/50
5641/5641 [==============================] - 6s 1ms/step - loss: 2.6937 - mae: 0.7186 - val_loss: 2.5760 - val_mae: 0.7054
Epoch 3/50
5641/5641 [==============================] - 6s 1ms/step - loss: 2.6189 - mae: 0.6916 - val_loss: 2.5172 - val_mae: 0.7004
Epoch 4/50
5641/5641 [==============================] - 6s 1ms/step - loss: 2.5895 - mae: 0.6763 - val_loss: 2.5238 - val_mae: 0.6315
Epoch 5/50
5641/5641 [==============================] - 6s 1ms/step - loss: 2.5485 - mae: 0.6660 - val_loss: 2.5443 - val_mae: 0.6642
Epoch 6/50
5641/5641 [==============================] - 6s 1ms/step - loss: 2.5341 - mae: 0.6601 - val_loss: 2.5010 - val_mae: 0.6379
Epoch 7/50
5641/5641 [==============================] - 6s 1ms/step - loss: 2.5233 - mae: 0.6554 - val_loss: 2.5337 - val_mae: 0.7485
Epoch 8/50
5641/5641 [==============================] - 6s 1ms

In [35]:
print(history.history['loss'])

[3.8541500568389893, 2.693690061569214, 2.618940830230713, 2.589465618133545, 2.548543930053711, 2.5341315269470215, 2.52327299118042, 2.506373167037964, 2.503011465072632, 2.491140127182007, 2.484548568725586, 2.4728188514709473, 2.4659409523010254, 2.450366735458374, 2.4531538486480713, 2.4423952102661133, 2.438080072402954, 2.423020362854004, 2.42661190032959, 2.413212776184082, 2.4124786853790283, 2.4062912464141846, 2.3978254795074463, 2.398772954940796, 2.391292095184326, 2.3874495029449463, 2.379371404647827, 2.381991147994995, 2.3748486042022705, 2.37863826751709, 2.3677425384521484, 2.367727518081665, 2.362107515335083, 2.3588643074035645, 2.3504881858825684, 2.3555757999420166, 2.3522164821624756, 2.353780508041382, 2.351271629333496, 2.3444840908050537, 2.339914321899414, 2.336308717727661, 2.3357136249542236, 2.3409454822540283, 2.3273837566375732, 2.331853151321411, 2.330188274383545, 2.3260934352874756, 2.322073221206665, 2.3303370475769043]


In [38]:
# Evaluate the model on the test data using `evaluate`
print("Evaluate on test data")
results = model.evaluate(test_features, test_labels, batch_size=32)
print("test loss, test acc:", results)

# Generate predictions (probabilities -- the output of the last layer)
# on new data using `predict`
print("Generate predictions for 3 samples")
predictions = model.predict(test_features[:3])
print("predictions shape:", predictions.shape)

Evaluate on test data
1411/1411 [==============================] - 1s 828us/step - loss: 2.4022 - mae: 0.5942
test loss, test acc: [2.402242660522461, 0.5942137837409973]
Generate predictions for 3 samples
1/1 [==============================] - 0s 23ms/step
predictions shape: (3, 1)


In [39]:
predictions

array([[0.10939732],
       [0.10939732],
       [0.10939732]], dtype=float32)

In [40]:
model.compile(
    optimizer=keras.optimizers.RMSprop(learning_rate=1e-3),
    loss=keras.losses.SparseCategoricalCrossentropy(),
    metrics=[keras.metrics.SparseCategoricalAccuracy()],
)